<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE locale [
<!ELEMENT locale (exception)>
<!ELEMENT exception (ANY)+>
<!ELEMENT warning (message)+>
<!ELEMENT error (message)+>
<!ELEMENT fatalerror (message)+>
<!ELEMENT message (#PCDATA)>
<!ATTLIST locale name CDATA #REQUIRED>
<!ATTLIST message name CDATA #REQUIRED>
]>
<locale name="english">
  <exception>
    <blob>
      <error>
        <message name="UnableToOpenBlob">
          unable to open image
        </message>
        <message name="UnableToOpenFile">
          unable to open file
        </message>
        <message name="UnableToReadBlob">
          unable to read blob
        </message>
        <message name="UnableToWriteBlob">
          unable to write blob
        </message>
        <message name="UnrecognizedImageFormat">
          unrecognized image format
        </message>
        <message name="ZeroLengthBlobNotPermitted">
          zero-length blob not permitted
        </message>
      </error>
    </blob>
    <cache>
      <error>
        <message name="CacheResourcesExhausted">
          cache resources exhausted
        </message>
        <message name="IncompatibleAPI">
          incompatible API
        </message>
        <message name="NoPixelsDefinedInCache">
          no pixels defined in cache
        </message>
        <message name="PixelCacheIsNotOpen">
          pixel cache is not open
        </message>
        <message name="PixelsAreNotAuthentic">
          pixels are not authentic
        </message>
        <message name="UnableToCloneCache">
          unable to clone cache
        </message>
        <message name="UnableToExtendCache">
          unable to extend cache
        </message>
        <message name="UnableToGetCacheNexus">
          unable to get cache nexus
        </message>
        <message name="UnableToOpenPixelCache">
          unable to open pixel cache
        </message>
        <message name="UnableToPersistPixelCache">
          unable to persist pixel cache
        </message>
        <message name="UnableToReadPixelCache">
          unable to read pixel cache
        </message>
        <message name="UnableToWritePixelCache">
          unable to write pixel cache
        </message>
      </error>
      <fatalerror>
        <message name="UnableToAcquireCacheView">
          unable to acquire cache view
        </message>
        <message name="UnableToExtendPixelCache">
          unable to extend pixel cache
        </message>
      </fatalerror>
    </cache>
    <coder>
      <error>
        <message name="ColormapTypeNotSupported">
          colormap type not supported
        </message>
        <message name="ColorspaceModelIsNotSupported">
          colorspace model is not supported
        </message>
        <message name="CompressNotSupported">
          compression not supported
        </message>
        <message name="DataEncodingSchemeIsNotSupported">
          data encoding scheme is not supported
        </message>
        <message name="DataStorageTypeIsNotSupported">
          data storage type is not supported
        </message>
        <message name="DeltaPNGNotSupported">
          delta-PNG is not supported
        </message>
        <message name="EncryptedWPGImageFileNotSupported">
          encrypted WPG image file not supported
        </message>
        <message name="FractalCompressNotSupported">
          fractal compression not supported
        </message>
        <message name="ImageColumnOrRowSizeIsNotSupported">
          image column or row size is not supported
        </message>
        <message name="ImageDoesNotHaveAClipMask">
          image does not have a clip mask
        </message>
        <message name="ImageDoesNotHaveAnAlphaChannel">
          image does not have an alpha channel
        </message>
        <message name="ImageDoesNotHaveAMaskChannel">
          image does not have an mask channel
        </message>
        <message name="ImageDoesNotHaveAThumbnail">
          image does not have a EXIF thumbnail
        </message>
        <message name="ImageIsNotTiled">
          image is not tiled
        </message>
        <message name="IrregularChannelGeometryNotSupported">
          irregular channel geometry not supported
        </message>
        <message name="JNGCompressNotSupported">
          JNG compression not supported
        </message>
        <message name="JPEGCompressNotSupported">
          JPEG compression not supported
        </message>
        <message name="JPEGEmbeddingFailed">
          JPEG embedding failed
        </message>
        <message name="LocationTypeIsNotSupported">
          location type is not supported
        </message>
        <message name="MapStorageTypeIsNotSupported">
          map storage type is not supported
        </message>
        <message name="MultidimensionalMatricesAreNotSupported">
          multi-dimensional matrices are not supported
        </message>
        <message name="MultipleRecordListNotSupported">
          multiple record list not supported
        </message>
        <message name="NoBitmapOnClipboard">
          no bitmap on clipboard
        </message>
        <message name="NoAPP1DataIsAvailable">
          no APP1 data is available
        </message>
        <message name="No8BIMDataIsAvailable">
          no 8BIM data is available
        </message>
        <message name="NoColorProfileIsAvailable">
          no color profile is available
        </message>
        <message name="NoDataReturned">
          no data returned
        </message>
        <message name="NoImageVectorGraphics">
          no image vector graphics; unable to generate SVG
        </message>
        <message name="NoIPTCProfileAvailable">
          no IPTC profile available
        </message>
        <message name="NumberOfImagesIsNotSupported">
          number of images is not supported
        </message>
        <message name="OnlyContinuousTonePictureSupported">
          only continuous tone picture supported
        </message>
        <message name="OnlyLevelZerofilesSupported">
          only level zero files Supported
        </message>
        <message name="PNGCompressNotSupported">
          PNG compression not supported
        </message>
        <message name="RLECompressNotSupported">
          RLE compression not supported
        </message>
        <message name="UnableToCopyProfile">
          unable to copy profile
        </message>
        <message name="UnableToCreateBitmap">
          unable to create bitmap
        </message>
        <message name="UnableToCreateADC">
          unable to create a DC
        </message>
        <message name="UnableToDecompressImage">
          unable to decompress image
        </message>
        <message name="UnableToWriteMPEGParameters">
          unable to write MPEG parameters
        </message>
        <message name="UnableToZipCompressImage">
          unable to zip-compress image
        </message>
        <message name="ZIPCompressNotSupported">
          ZIP compression not supported
        </message>
      </error>
      <warning>
        <message name="ExifProfileSizeExceedsLimit">
          exif profile size exceeds limit and will be truncated
        </message>
        <message name="LosslessToLossyJPEGConversion">
          lossless to lossy JPEG conversion
        </message>
      </warning>
    </coder>
    <configure>
      <error>
        <message name="IncludeElementNestedTooDeeply">
          include element nested too deeply
        </message>
        <message name="PolicyValidationException">
          security policy failed to validate
        </message>
      </error>
      <warning>
        <message name="UnableToOpenConfigureFile">
          unable to access configure file
        </message>
        <message name="UnableToOpenModuleFile">
          unable to open module file
        </message>
      </warning>
    </configure>
    <corrupt>
      <image>
        <error>
          <message name="AnErrorHasOccurredReadingFromFile">
            an error has occurred reading from file
          </message>
          <message name="AnErrorHasOccurredWritingToFile">
            an error has occurred writing to file
          </message>
          <message name="CipherSupportNotEnabled">
            cipher support not enabled
          </message>
          <message name="ColormapExceeds256Colors">
            colormap exceeded 256 colors
          </message>
          <message name="CorruptImage">
            corrupt image
          </message>
          <message name="FileFormatVersionMismatch">
            file format version mismatch
          </message>
          <message name="ImageDepthNotSupported">
            image depth not supported
          </message>
          <message name="ImageFileDoesNotContainAnyImageData">
            image file does not contain any image data
          </message>
          <message name="ImageTypeNotSupported">
            image type not supported
          </message>
          <message name="ImproperImageHeader">
            improper image header
          </message>
          <message name="InsufficientImageDataInFile">
            insufficient image data in file
          </message>
          <message name="InvalidColormapIndex">
            invalid colormap index
          </message>
          <message name="InvalidPixel">
            invalid pixel
          </message>
          <message name="LengthAndFilesizeDoNotMatch">
            length and filesize do not match
          </message>
          <message name="MaximumChannelsExceeded">
            maximum channels exceeded
          </message>
          <message name="MissingImageChannel">
            missing image channel
          </message>
          <message name="NegativeOrZeroImageSize">
            negative or zero image size
          </message>
          <message name="NonOS2HeaderSizeError">
            non OS2 BMP header size less than 40
          </message>
          <message name="NotEnoughPixelData">
            not enough pixel data
          </message>
          <message name="NotEnoughTiles">
            not enough tiles found in level
          </message>
          <message name="TooMuchImageDataInFile">
            too much image data in file
          </message>
          <message name="StaticPlanesValueNotEqualToOne">
            static planes value not equal to 1
          </message>
          <message name="UnableToReadExtensionBlock">
            unable to read extension block
          </message>
          <message name="UnableToReadImageHeader">
            unable to read image header
          </message>
          <message name="UnableToReadImageData">
            unable to read image data
          </message>
          <message name="UnableToRunlengthDecodeImage">
            unable to runlength decode image
          </message>
          <message name="UnableToUncompressImage">
            unable to uncompress image
          </message>
          <message name="UnexpectedEndOfFile">
            unexpected end-of-file
          </message>
          <message name="UnexpectedSamplingFactor">
            unexpected sampling factor
          </message>
          <message name="UnknownPatternType">
            unknown pattern type
          </message>
          <message name="UnrecognizedAlphaChannelOption">
            unrecognized alpha channel option
          </message>
          <message name="UnrecognizedImageCompression">
            unrecognized compression
          </message>
          <message name="UnrecognizedNumberOfColors">
            unrecognized number of colors
          </message>
          <message name="UnsupportedBitsPerPixel">
            unsupported bits per pixel
          </message>
        </error>
        <fatalerror>
          <message name="UnableToPersistKey">
            unable to persist key
          </message>
        </fatalerror>
        <warning>
          <message name="InsufficientImageDataInFile">
            insufficient image data in file
          </message>
          <message name="LengthAndFilesizeDoNotMatch">
            length and filesize do not match
          </message>
          <message name="SkipToSyncByte">
            corrupt PCD image, skipping to sync byte
          </message>
        </warning>
      </image>
    </corrupt>
    <delegate>
      <error>
        <message name="DelegateFailed">
          delegate failed
        </message>
        <message name="FailedToComputeOutputSize">
          failed to compute output size
        </message>
        <message name="FailedToRenderFile">
          failed to render file
        </message>
        <message name="FailedToScanFile">
          failed to scan file
        </message>
        <message name="NoTagFound">
          no tag found
        </message>
        <message name="PCLDelegateFailed">
          PCL delegate failed
        </message>
        <message name="PostscriptDelegateFailed">
          Postscript delegate failed
        </message>
        <message name="UnableToCreateImage">
          unable to create image
        </message>
        <message name="UnableToDecodeImageFile">
          unable to decode image file
        </message>
        <message name="UnableToEncodeImageFile">
          unable to encode image file
        </message>
        <message name="UnableToInitializeFPXLibrary">
          unable to initialize FPX library
        </message>
        <message name="UnableToInitializeWMFLibrary">
          unable to initialize WMF library
        </message>
        <message name="UnableToManageJP2Stream">
          unable to manage JP2 stream
        </message>
        <message name="UnableToReadAspectRatio">
          unable to read aspect ratio
        </message>
        <message name="UnableToReadSummaryInfo">
          unable to read summary info
        </message>
        <message name="UnableToSetAffineMatrix">
          unable to set affine matrix
        </message>
        <message name="UnableToSetAspectRatio">
          unable to set aspect ratio
        </message>
        <message name="UnableToSetColorTwist">
          unable to set color twist
        </message>
        <message name="UnableToSetContrast">
          unable to set contrast
        </message>
        <message name="UnableToSetFilteringValue">
          unable to set filtering value
        </message>
        <message name="UnableToSetImageTitle">
          unable to set image title
        </message>
        <message name="UnableToSetJPEGLevel">
          unable to set JPEG level
        </message>
        <message name="UnableToSetRegionOfInterest">
          unable to set region of interest
        </message>
        <message name="UnableToSetSummaryInfo">
          unable to set summary info
        </message>
        <message name="UnableToWriteSVGFormat">
          unable to write SVG format
        </message>
        <message name="XPSDelegateFailed">
          XPS delegate failed
        </message>
      </error>
    </delegate>
    <draw>
      <error>
        <message name="AlreadyPushingPatternDefinition">
          already pushing pattern definition
        </message>
        <message name="NonconformingDrawingPrimitiveDefinition">
          non-conforming drawing primitive definition
        </message>
        <message name="NotARelativeURL">
          not a relative URL
        </message>
        <message name="NotCurrentlyPushingPatternDefinition">
          not currently pushing pattern definition
        </message>
        <message name="SegmentStackOverflow">
          segment stack overflow
        </message>
        <message name="TooManyBezierCoordinates">
          too many bezier coordinates
        </message>
        <message name="UnableToPrint">
          unable to print
        </message>
        <message name="UnbalancedGraphicContextPushPop">
          unbalanced graphic context push-pop
        </message>
        <message name="URLNotFound">
          URL not found
        </message>
        <message name="VectorGraphicsNestedTooDeeply">
          vector graphics nested too deeply
        </message>
      </error>
    </draw>
    <file>
      <open>
        <error>
          <message name="AnErrorHasOccurredReadingFromFile">
            an error has occurred reading from file
          </message>
          <message name="UnableToCreateTemporaryFile">
            unable to create temporary file
          </message>
          <message name="UnableToOpenFile">
            unable to open file
          </message>
          <message name="UnableToWriteFile">
            unable to write file
          </message>
        </error>
      </open>
    </file>
    <image>
      <error>
        <message name="AngleIsDiscontinuous">
          angle is discontinuous
        </message>
        <message name="ColormappedImageRequired">
          colormapped image required
        </message>
        <message name="ColorSeparatedImageRequired">
          color separated image required
        </message>
        <message name="ColorspaceColorProfileMismatch">
          color profile operates on another colorspace
        </message>
        <message name="ExplicitCoderNotAllowed">
          explicit coder not allowed
        </message>
        <message name="ImageDepthNotSupported">
          image depth not supported
        </message>
        <message name="ImageSequenceRequired">
          image sequence is required
        </message>
        <message name="ImageMorphologyDiffers">
          image morphology differs
        </message>
        <message name="ImageListRequired">
          image list is required
        </message>
        <message name="ImageSizeDiffers">
          image size differs
        </message>
        <message name="LeftAndRightImageSizesDiffer">
          left and right image sizes differ
        </message>
        <message name="ImageSizeLimitExceeded">
          Image dimension exceeds maximum supported size
        </message>
        <message name="NegativeOrZeroImageSize">
          negative or zero image size
        </message>
        <message name="NoImagesWereFound">
          no images were found
        </message>
        <message name="NoImagesWereLoaded">
          no images were loaded
        </message>
        <message name="TooManyClusters">
          too many cluster
        </message>
        <message name="UnableToCreateColorTransform">
          unable to create color transform
        </message>
        <message name="WidthOrHeightExceedsLimit">
          width or height exceeds limit
        </message>
      </error>
      <warning>
        <message name="AssociateProfile">
          associate profile with image, a source and destination color profile required for transform
        </message>
        <message name="ImagesTooDissimilar">
          images too dissimilar
        </message>
        <message name="UnableToTransformColorspace">
          unable to transform colorspace
        </message>
      </warning>
    </image>
    <filter>
      <error>
        <message name="FilterFailed">
          filter failed
        </message>
      </error>
    </filter>
    <missing>
      <delegate>
        <error>
          <message name="DelegateLibrarySupportNotBuiltIn">
            delegate library support not built-in
          </message>
          <message name="NoDecodeDelegateForThisImageFormat">
            no decode delegate for this image format
          </message>
          <message name="NoEncodeDelegateForThisImageFormat">
            no encode delegate for this image format
          </message>
        </error>
        <warning>
          <message name="DelegateLibrarySupportNotBuiltIn">
            delegate library support not built-in
          </message>
          <message name="FreeTypeLibraryIsNotAvailable">
            FreeType library is not available
          </message>
          <message name="LCMSLibraryIsNotAvailable">
            LCMS color profile library is not available
          </message>
          <message name="NoEncodeDelegateForThisImageFormat">
            no encode delegate for this image format
          </message>
        </warning>
      </delegate>
    </missing>
    <module>
      <error>
        <message name="ImageCoderSignatureMismatch">
          image coder signature mismatch
        </message>
        <message name="ImageFilterSignatureMismatch">
          image filter signature mismatch
        </message>
        <message name="UnableToLoadModule">
          unable to load module
        </message>
        <message name="UnableToRegisterImageFormat">
          unable to register image format
        </message>
      </error>
      <fatalerror>
        <message name="UnableToInitializeModuleLoader">
          unable to initialize module loader
        </message>
      </fatalerror>
      <warning>
        <message name="UnableToCloseModule">
          unable to close module
        </message>
      </warning>
    </module>
    <option>
      <error>
        <message name="ClutImageRequired">
          color lookup table image required
        </message>
        <message name="CompositeImageRequired">
          composite image required
        </message>
        <message name="CurlyBracesNestedTooDeeply">
          curly braces nested too deeply
        </message>
        <message name="DeprecatedOptionNoCode">
          option deprecated, unable to execute
        </message>
        <message name="DivideByZero">
          divide by zero
        </message>
        <message name="FrameIsLessThanImageSize">
          frame is less than image size
        </message>
        <message name="GeometryDimensionsAreZero">
          geometry dimensions are zero
        </message>
        <message name="GeometryDoesNotContainImage">
          geometry does not contain image
        </message>
        <message name="ImageSequenceRequired">
          image sequence is required
        </message>
        <message name="InterpretPropertyFailure">
          failure to interpret image property escapes
        </message>
        <message name="InvalidArgument">
          invalid argument for option
        </message>
        <message name="InvalidUseOfOption">
          invalid use of option
        </message>
        <message name="InvalidGeometry">
          invalid geometry
        </message>
        <message name="InvalidImageIndex">
          invalid image index
        </message>
        <message name="InvalidNumberList">
          invalid list of numbers
        </message>
        <message name="InvalidSetting">
          invalid setting
        </message>
        <message name="ImagesAreNotTheSameSize">
          images are not the same size
        </message>
        <message name="ImagePagesAreNotCoalesced">
          image pages are not coalesced
        </message>
        <message name="ImageSizeMustExceedBevelWidth">
          size must exceed bevel width
        </message>
        <message name="ImageWidthsOrHeightsDiffer">
          image widths or heights differ
        </message>
        <message name="KernelWidthMustBeAnOddNumber">
          kernel width must be an odd number
        </message>
        <message name="LabelExpected">
          label expected
        </message>
        <message name="MapImageRequired">
          map image required
        </message>
        <message name="MissingArgument">
          missing required argument
        </message>
        <message name="MissingAnImageFilename">
          missing an image filename
        </message>
        <message name="MissingExpression">
          missing expression
        </message>
        <message name="MissingNullSeparator">
          missing Null Image List Separator
        </message>
        <message name="MissingOutputFilename">
          missing output filename
        </message>
        <message name="MustSpecifyAnImageName">
          must specify an image name
        </message>
        <message name="MustSpecifyImageDepth">
          must specify image depth
        </message>
        <message name="MustSpecifyImageSize">
          must specify image size
        </message>
        <message name="NoBlobDefined">
          no Binary Large OBjects defined
        </message>
        <message name="NoClipPathDefined">
          no clip path defined
        </message>
        <message name="NoImagesForWrite">
          no images for write
        </message>
        <message name="NoImagesFound">
          no images found for operation
        </message>
        <message name="NoImagesDefined">
          no images defined
        </message>
        <message name="NoImageVectorGraphics">
          no image vector graphics
        </message>
        <message name="NoSuchImage">
          no such image
        </message>
        <message name="NoSuchImageChannel">
          no such image channel
        </message>
        <message name="NoSuchOption">
          no such option
        </message>
        <message name="NonZeroWidthAndHeightRequired">
          non-zero width and height required
        </message>
        <message name="NotEnoughParameters">
          not enough parameters
        </message>
        <message name="ParenthesisNestedTooDeeply">
          parenthesis nested too deeply
        </message>
        <message name="ReferenceImageRequired">
          reference image required
        </message>
        <message name="ReferenceIsNotMyType">
          reference is not my type
        </message>
        <message name="SetReadOnlyProperty">
          attempt to set read-only property
        </message>
        <message name="SteganoImageRequired">
          stegano image required
        </message>
        <message name="StereoImageRequired">
          stereo image required
        </message>
        <message name="SubimageSpecificationReturnsNoImages">
          subimage specification returns no images
        </message>
        <message name="TwoOrMoreImagesRequired">
          two or more images required
        </message>
        <message name="UnableToAccessPath">
          unable to access file path
        </message>
        <message name="UnableToOpenFile">
          unable to open file
        </message>
        <message name="UnableToParseExpression">
          unable to parse expression
        </message>
        <message name="UnableToParseKernel">
          unable to parse kernel string
        </message>
        <message name="UnbalancedBraces">
          unbalanced braces
        </message>
        <message name="UnbalancedParenthesis">
          unbalanced parenthesis
        </message>
        <message name="UndefinedVariable">
          undefined variable
        </message>
        <message name="UnrecognizedAttribute">
          unrecognized attribute
        </message>
        <message name="UnrecognizedChannelType">
          unrecognized channel type
        </message>
        <message name="UnrecognizedColor">
          unrecognized color
        </message>
        <message name="UnrecognizedColorspace">
          unrecognized colorspace
        </message>
        <message name="UnrecognizedComposeOperator">
          unrecognized compose operator
        </message>
        <message name="UnrecognizedCompressType">
          unrecognized compress type
        </message>
        <message name="UnrecognizedDirectionType">
          unrecognized direction type
        </message>
        <message name="UnrecognizedDisposeMethod">
          unrecognized dispose method
        </message>
        <message name="UnrecognizedDistortMethod">
          unrecognized distortion method
        </message>
        <message name="UnrecognizedDitherMethod">
          unrecognized dither method
        </message>
        <message name="UnrecognizedEndianType">
          unrecognized endian type
        </message>
        <message name="UnrecognizedElement">
          unrecognized element
        </message>
        <message name="UnrecognizedEvaluateOperator">
          unrecognized evaluate operator
        </message>
        <message name="UnrecognizedEventType">
          unrecognized event type
        </message>
        <message name="UnrecognizedFunction">
          unrecognized function
        </message>
        <message name="UnrecognizedGravityType">
          unrecognized gravity type
        </message>
        <message name="UnrecognizedImageCompression">
          unrecognized image compression
        </message>
        <message name="UnrecognizedImageFilter">
          unrecognized image filter
        </message>
        <message name="UnrecognizedImageFormat">
          unrecognized image format
        </message>
        <message name="UnrecognizedImageMode">
          unrecognized image mode
        </message>
        <message name="UnrecognizedImageOrientation">
          unrecognized image orientation
        </message>
        <message name="UnrecognizedImageType">
          unrecognized image type
        </message>
        <message name="UnrecognizedIntentType">
          unrecognized intent type
        </message>
        <message name="UnrecognizedInterlaceType">
          unrecognized interlace type
        </message>
        <message name="UnrecognizedInterpolateMethod">
          unrecognized interpolate method
        </message>
        <message name="UnrecognizedKernelType">
          unrecognized kernel type
        </message>
        <message name="UnrecognizedListType">
          unrecognized list type
        </message>
        <message name="UnrecognizedMetricType">
          unrecognized metric type
        </message>
        <message name="UnrecognizedModeType">
          unrecognized mode type
        </message>
        <message name="UnrecognizedMorphologyMethod">